### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by Tristor** [jbreams/gonepass#1]
This fails to build on FreeBSD as-is because the Makefile specifically sets "CC" to "gcc", on FreeBSD the default compiler is clang, but gcc can be installed.  When it's installed, it creates a version named binary such as gcc48, gcc49, etc.  By changing the Makefile to say "CC=gcc49" I was able to get it to compile.  There needs to be some detection routine (well that's really what autoconf is for) to identify which compiler to use.  I didn't see anything which specifically required gcc, so this should in theory build cleanly under clang on FreeBSD.

Just filing this as a heads-up.

**Comment by jbreams** [comment]
Yeah, I need a real build system instead of a makefile, sorry about that! I'll work on it and keep this open until I've got a build system in place.

**Comment by jbreams** [comment]
I just put in a simple cmake build system. Can you try it out on FreeBSD?

**Comment by Tristor** [comment]
I'll give it a shot sometime tomorrow when I get a chance.

**Comment by valpackett** [comment]
This should be closed. Builds fine these days, and I've submitted it for packaging: 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226706
