### ISSUE TITLE
Application window defaults to 148x256 pixels, which is too small to see any information or password entry field

### ISSUE THREAD

**Issue by agsimmons** [jbreams/gonepass#15]
Desktop Environment: Gnome v3.20

![](http://i.imgur.com/wl7wnRi.png)

**Comment by jbreams** [comment]
Oof, that's definitely a bad default. Not something I see with my window manager, so I'll figure out how to fix it for everyone else.

**Comment by jbreams** [comment]
I think this was fixed in https://github.com/jbreams/gonepass/pull/20
