### ISSUE TITLE
Vault password entry field does not automatically show up on program start

### ISSUE THREAD

**Issue by agsimmons** [jbreams/gonepass#16]
The vault must be selected from the lock menu. Instead, I believe it would make more sense to automatically bring up the password entry field for the previously opened vault.

**Comment by jbreams** [comment]
That should already be the behavior. Sounds like a bug to me. I'll check it out.

**Comment by jbreams** [comment]
I think I figured this out and fixed it today in e311bd7d3331766b7fcd23fe617376c18f990c81
