### ISSUE TITLE
This is a command line app right?

### ISSUE THREAD

**Issue by jonnybarnes** [jbreams/gonepass#2]
I think I got this installed correctly on Arch Linux (though I had to edit the [PKGBUILD](https://gist.github.com/jonnybarnes/d8f0bfd85627561dccbf)) but I'm having to start this from the terminal in GNOME. Is that right?

**Comment by jbreams** [comment]
No, its a gnome app. There's no CLI.

**Comment by jonnybarnes** [comment]
Hmmm, I must have installed it wrong then, cause I can't start it from GNOME: http://imgur.com/PRVbd1L

**Comment by jbreams** [comment]
I think I'm missing a .desktop file that would make it show up in a search like that. I'll add one and test it later today. I also think I'm missing something in the PKGBUILD file to compile/install the gsettings schema.

**Comment by jbreams** [comment]
Hi, sorry it took so long to work on this. I think everything should be fixed now, and I've updated the arch package with your changes. Let me know if you have any more trouble!

**Comment by jonnybarnes** [comment]
Sorry its taken so long to reply but I've been away from home for the last two weeks.

This is how I've got it working, though I did _steal_ 1password’s logo: https://gist.github.com/jonnybarnes/d8f0bfd85627561dccb

**Comment by jbreams** [comment]
No worries, I added a desktop/icon file to the repo and updated the arch package to use them. Thanks for following up!

**Comment by jonnybarnes** [comment]
The AUR package doesn’t include the .desktop and .install file.

**Comment by jbreams** [comment]
The build system installs the .desktop/icon file in the pkgbuild install root. So the AUR package should install those files in the right places. This is what it looks like on my system.

```
jreams@intrepid: ~
 $ pacman -Qo /usr/share/pixmaps/gonepass.png /usr/share/applications/gonepass.desktop                       
/usr/share/pixmaps/gonepass.png is owned by gonepass-git r26.c103859-1
/usr/share/applications/gonepass.desktop is owned by gonepass-git r26.c103859-1
```

**Comment by jonnybarnes** [comment]
Oh cool, didn’t know you could do that from within a package. :)
