### ISSUE TITLE
Error unlocking 1password file

### ISSUE THREAD

**Issue by sequoia-hope** [jbreams/gonepass#3]
I can't seem to unlock my 1pass file. I get the following error:

Error loading encryption keys! \u0000 is not allowed without JSON_ALLOW_NUL

This is on a fresh Debian 8.0 install, with all of the dependencies also freshly installed.

My version of 1pass is not the latest version I believe, but I'd have to check which version that is, if it mattered.

Any ideas?

**Comment by jbreams** [comment]
Well, from the error message, it sounds like there's a null byte in the values of one of the fields in the encryption keys file. I don't have any password vaults like this, but it's easy enough to tell the JSON parser to allow this behavior. I just pushed a new commit that does this, let me know if this fixes your issue.

**Comment by sequoia-hope** [comment]
That fixes that issue. Now I have a new issue, so I'll open a new one. Thanks!
